/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasAlumnos;

import Ventanas.VentanaGraficarAlumno;
import Utilidades.BusquedasMongo;
import Utilidades.CargarTablas;
import com.itextpdf.text.BadElementException;
import com.mongodb.DBCursor;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author 3medi
 */
public class VentanasAsignaturas extends javax.swing.JFrame {

    private int cod;
    private CargarTablas cargarTablas;
    private BusquedasMongo buscar;
    private DBCursor cursor;
    private String nombreAlumno;

    //Constructor principal que recibe el codigo del alumno y su nombre
    public VentanasAsignaturas(int cod, String nombreAlumno) {
        initComponents();
        this.setVisible(true);
        setLocationRelativeTo(null);
        this.cod = cod;
        cargarTablas = new CargarTablas();
        cargarTablas.cargarTablaAsignaturasPorCodAlumno(this, cod);
        this.nombreAlumno = nombreAlumno;

    }

    private VentanasAsignaturas() {
        System.out.println("Para acceder a la aplicación tiene que iniciar desde el login.");
    }

    public JTable getTablaVisible() {
        return TablaVisible;
    }

    public void setTablaVisible(JTable TablaVisible) {
        this.TablaVisible = TablaVisible;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVisible = new javax.swing.JTable();
        Busquedas = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        cargarTabla = new javax.swing.JButton();
        graficar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        RutaCompleta = new javax.swing.JTextField();
        botonRutar = new javax.swing.JButton();
        reporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado asignaturas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 2, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(102, 0, 204));

        TablaVisible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaVisible);

        Busquedas.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N
        Busquedas.setToolTipText("Inserte el nombre de la asignatura");

        jButtonBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBuscar.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-acercar-20.png"))); // NOI18N
        jButtonBuscar.setToolTipText("Buscar por nombre de  asignatura");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        cargarTabla.setBackground(new java.awt.Color(0, 0, 0));
        cargarTabla.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        cargarTabla.setForeground(new java.awt.Color(255, 255, 255));
        cargarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-actualizar-20.png"))); // NOI18N
        cargarTabla.setToolTipText("Cargar listado principal");
        cargarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarTablaActionPerformed(evt);
            }
        });

        graficar.setBackground(new java.awt.Color(0, 0, 0));
        graficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-gráfico-de-barras-30.png"))); // NOI18N
        graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Busquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar)
                        .addGap(22, 22, 22)
                        .addComponent(cargarTabla)
                        .addGap(22, 22, 22)
                        .addComponent(graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cargarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Busquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(graficar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        botonVolver.setBackground(new java.awt.Color(0, 0, 0));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-volver-50.png"))); // NOI18N
        botonVolver.setToolTipText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 0, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reportes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Baskerville Old Face", 2, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        RutaCompleta.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N

        botonRutar.setBackground(new java.awt.Color(0, 0, 0));
        botonRutar.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        botonRutar.setForeground(new java.awt.Color(255, 255, 255));
        botonRutar.setText("Ruta");
        botonRutar.setToolTipText("Lugar donde deseamos que se guarde el pdf.");
        botonRutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRutarActionPerformed(evt);
            }
        });

        reporte.setBackground(new java.awt.Color(0, 0, 0));
        reporte.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        reporte.setForeground(new java.awt.Color(255, 255, 255));
        reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-reporte-de-negocios-30.png"))); // NOI18N
        reporte.setToolTipText("Se sacara un pdf con la información de las tablas");
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RutaCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRutar)
                .addGap(27, 27, 27)
                .addComponent(reporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRutar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RutaCompleta))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed

        //botón para volver atras 
        dispose();

    }//GEN-LAST:event_botonVolverActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       //Inicializamos nuestros objetos
        buscar = new BusquedasMongo();
        cargarTablas = new CargarTablas();
        //Si las busquedas estan en blanco salta un mensaje
        if (Busquedas.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No ha puesto ninguna asignatura.");
        } else {
            //Buscamos las asignaturas por nombre
            cursor = buscar.buscarTodasNotasNombre(Busquedas.getText(), cod);
            System.out.println(cursor.size());

            try {
                //Si lo encuentra carga las tablas y limpia las busquedas 
                if (cursor.size() != 0) {
                    try {
                        cargarTablas.cargarTablaAsignaturasPorNombre(this, cursor);
                        Busquedas.setText("");
                    } catch (NullPointerException e) {

                    }
                }
                //En el caso de que no lo encuentre saltará un mensaje
                if (cursor.size() == 0) {
                    JOptionPane.showMessageDialog(this, "No tiene notas en esa asignatura  " + Busquedas.getText());
                    Busquedas.setText("");

                }

            } finally {
                cursor.close();

            }

        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void cargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarTablaActionPerformed
        // Botón que llama al metodo de cargar las tablas 
        cargarTablas = new CargarTablas();
        cargarTablas.cargarTablaAsignaturasPorCodAlumno(this, cod);
    }//GEN-LAST:event_cargarTablaActionPerformed

    private void graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficarActionPerformed
        // Llamamos a la ventana de graficar
        Ventanas.VentanaGraficarAlumno ventanaGraficarAlumno = new VentanaGraficarAlumno(this);

        //Nos generamos un objeto de tipo DefaultCategoryDataset
        DefaultCategoryDataset barChartDataset = new DefaultCategoryDataset();
        //Recorremos la tabla y sacamos los valores de la misma para mandarlos a la gráfica 
        for (int i = 0; i < TablaVisible.getRowCount(); i++) {
            barChartDataset.setValue(Integer.parseInt(TablaVisible.getValueAt(i, 2).toString()), TablaVisible.getValueAt(i, 3).toString(), TablaVisible.getValueAt(i, 1).toString());
        }
        //Creamos la gráfica
        JFreeChart barChart = ChartFactory.createBarChart3D("Grafica de " + nombreAlumno, "Fechas", "Notas", barChartDataset, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot bPlot = barChart.getCategoryPlot();
        bPlot.setRangeGridlinePaint(Color.ORANGE);

        //Generamos un ChartPanel y le asignamos las dimensiones 
        ChartPanel baPanel = new ChartPanel(barChart);
        baPanel.setBounds(500, 40, 500, 400);
        
        //Borramos el contenido del panel y le añadimos el CharPanel
        ventanaGraficarAlumno.getjPanel1().removeAll();
        ventanaGraficarAlumno.getjPanel1().add(baPanel, BorderLayout.CENTER);
        ventanaGraficarAlumno.getjPanel1().validate();

        this.setVisible(false);
    }//GEN-LAST:event_graficarActionPerformed

    private void botonRutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRutarActionPerformed
        // Botón que nos permite buscar la ruta donde pondremos nuestro documento 
        JFileChooser dlg = new JFileChooser();
        int op = dlg.showSaveDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            RutaCompleta.setText(f.toString());
        }
    }//GEN-LAST:event_botonRutarActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
       
        //Guardamos el valor de la ruta y nos generamos un documento
        String ruta = RutaCompleta.getText();
        Document doc = new Document();
        try {
            //Si tenemos ruta
            if (!ruta.equalsIgnoreCase("")) {
                //Creamos un FileOutputStream de tipo pdf y le asignamos el nombre que le hemos puesto y la ruta 
                FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");

                //Escribimos en el pdf y abrimos el documento 
                PdfWriter pdf = PdfWriter.getInstance(doc, archivo);
                doc.open();

                //Le asignamos al documento una imagen 
                Image imagenes = Image.getInstance("src/Imagenes/notas.png");
                doc.add(imagenes);

                //Creamos un contenedor para el pdf 
                PdfContentByte cb = pdf.getDirectContent();

                //Le asignamos el tipo de fuente
                BaseFont bf = BaseFont.createFont(BaseFont.COURIER_BOLD, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);

                //Abrimos la zona de editar texto
                cb.beginText();

                cb.setFontAndSize(bf, 30);
                cb.setTextMatrix(50, 450);
                cb.showText("Calificaciones de " + nombreAlumno);

                cb.setFontAndSize(bf, 14);
                int y = 400;
                //For que recorre la tabla y va colocando los datos que hemos sacado de la tabla
                for (int i = 0; i < TablaVisible.getRowCount(); i++) {
                    y = y - 20;
                    cb.setTextMatrix(50, y);
                    cb.showText("Asignatura: " + TablaVisible.getValueAt(i, 1).toString() + "|| Nota: " + TablaVisible.getValueAt(i, 2).toString() + "|| Fecha: " + TablaVisible.getValueAt(i, 3).toString());
                }

                //Cerramos la zona de texto
                cb.endText();

                //Cerramos el documento
                doc.close();
                JOptionPane.showMessageDialog(this, "Pdf creado");
            }else{
                JOptionPane.showMessageDialog(this, "No ha puesto ninguna ruta, por favor introduzcala.");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanasAsignaturas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BadElementException ex) {
            System.out.println("La ruta de la imagen esta mal.");
        } catch (IOException ex) {
            Logger.getLogger(VentanasAsignaturas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            System.out.println("Hay problemas con el documento.");
        }
    }//GEN-LAST:event_reporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanasAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanasAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanasAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanasAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanasAsignaturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Busquedas;
    private javax.swing.JTextField RutaCompleta;
    private javax.swing.JTable TablaVisible;
    private javax.swing.JButton botonRutar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton cargarTabla;
    private javax.swing.JButton graficar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reporte;
    // End of variables declaration//GEN-END:variables
}
