/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Beans.Alumnos;
import Beans.Profesores;
import Utilidades.BusquedasMongo;
import Ventanas.VentanaAdmin;
import Ventanas.VentanaAlumno;
import Ventanas.VentanaCambiarContrasenia;
import Ventanas.VentanaProfesor;
import Ventanas.VentanaRegistrarse;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import com.sun.glass.events.KeyEvent;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author 3medi
 */
public class VentanaDeInicio extends javax.swing.JFrame {

    
    private int i = 0;
    private BusquedasMongo buscar;

    /**
     * Creates new form VentanaDeInicio
     */
    public VentanaDeInicio() {
        //Constructor principal que se ejecuta al comienzo de la aplicación
        initComponents();
        this.setVisible(true);
        setLocationRelativeTo(null);

    }

    public void clear() {
        //Limpiar los campos de textos del logeo
        Nombre.setText("");
        Contrasenia.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Registrarse = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        jButtonlogeo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cambiarContrasenia = new javax.swing.JLabel();
        Contrasenia = new javax.swing.JPasswordField();
        visible_code = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/38e01f84707332276df64d1260f844d6.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("<html><center>Si todavia no se ha registrado, </br>dele a registarse para poder hacerlo.</center></html>");

        Registrarse.setBackground(new java.awt.Color(255, 255, 255));
        Registrarse.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        Registrarse.setForeground(new java.awt.Color(255, 255, 255));
        Registrarse.setText("Registrarse");
        Registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarseMouseExited(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Salir.setBackground(new java.awt.Color(0, 0, 0));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-apagar-64.png"))); // NOI18N
        Salir.setToolTipText("Salir de la aplicación");
        Salir.setBorder(null);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jButtonlogeo.setBackground(new java.awt.Color(0, 0, 0));
        jButtonlogeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-accede-redondeado-derecho-64.png"))); // NOI18N
        jButtonlogeo.setToolTipText("Logearse");
        jButtonlogeo.setBorder(null);
        jButtonlogeo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonlogeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlogeoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña");

        Nombre.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Inicio de sesión");

        cambiarContrasenia.setFont(new java.awt.Font("Bookman Old Style", 2, 11)); // NOI18N
        cambiarContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        cambiarContrasenia.setText("¿Olvidaste tu contraseña?");
        cambiarContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiarContraseniaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cambiarContraseniaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cambiarContraseniaMouseExited(evt);
            }
        });

        Contrasenia.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N
        Contrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ContraseniaKeyReleased(evt);
            }
        });

        visible_code.setBackground(new java.awt.Color(0, 0, 0));
        visible_code.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-visible-20.png"))); // NOI18N
        visible_code.setToolTipText("Ocultar/mostrar contraseña");
        visible_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visible_codeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 184, Short.MAX_VALUE)
                .addComponent(jButtonlogeo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(141, 141, 141)
                                    .addComponent(Registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel7))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(75, 75, 75))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(visible_code, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(cambiarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(visible_code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contrasenia))
                .addGap(13, 13, 13)
                .addComponent(cambiarContrasenia)
                .addGap(21, 21, 21)
                .addComponent(jButtonlogeo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Registrarse)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseMouseClicked
        //Hipervinculo que manda a la ventana registrarse 
        VentanaRegistrarse ventanaRegistrarse = new VentanaRegistrarse(this);
        clear();
        setVisible(false);

    }//GEN-LAST:event_RegistrarseMouseClicked

    private void RegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseMouseEntered
        // Cuando pasa por encima de texto se cambia de color

        Registrarse.setForeground(Color.BLACK);
    }//GEN-LAST:event_RegistrarseMouseEntered

    private void RegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseMouseExited
        //Si existe el mause encima del texto se cambia de color 
        Registrarse.setForeground(Color.WHITE);
    }//GEN-LAST:event_RegistrarseMouseExited

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // Boton para salir de la aplicación, pide confirmación.

        int advertencia = JOptionPane.showConfirmDialog(null, "¿Está seguro de salir de la aplicación?");

        if (advertencia == JOptionPane.YES_OPTION) {
            System.exit(1);
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void jButtonlogeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlogeoActionPerformed
        // Boton que llama a la acción logearse
        buscar = new BusquedasMongo();
        validarEntrada(buscar);

    }//GEN-LAST:event_jButtonlogeoActionPerformed

    private void cambiarContraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarContraseniaMouseClicked
        // Hipervinculo que nos manda a la ventana de cambiar contraseña
        VentanaCambiarContrasenia ventanaCambiarContrasenia = new VentanaCambiarContrasenia(this);
        clear();
        this.setVisible(false);
    }//GEN-LAST:event_cambiarContraseniaMouseClicked

    private void cambiarContraseniaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarContraseniaMouseEntered
        // Al igual que con el registro, si pasa por encima el raton cambia de color
        cambiarContrasenia.setForeground(Color.BLACK);
    }//GEN-LAST:event_cambiarContraseniaMouseEntered

    private void cambiarContraseniaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarContraseniaMouseExited
        //Al igual que con el registro, el texto cambia de color con la exictencia del ratón
        cambiarContrasenia.setForeground(Color.WHITE);
    }//GEN-LAST:event_cambiarContraseniaMouseExited

    private void visible_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visible_codeActionPerformed
        // Boton que sirve para cambiar de contraseña oculta a visible

        if (i == 0) {
            Contrasenia.setEchoChar((char) 0);
            i = 1;
        } else {
            Contrasenia.setEchoChar('*');
            i = 0;
        }

    }//GEN-LAST:event_visible_codeActionPerformed

    private void ContraseniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseniaKeyReleased
        // Si el pulsamos la tecla enter cuando estamos encima de la contraseña, se ejecuta la acción de logeo
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscar = new BusquedasMongo();
            validarEntrada(buscar);
        }
    }//GEN-LAST:event_ContraseniaKeyReleased

    //Zona de get and set
    public JButton getjButton1() {
        return jButtonlogeo;
    }

    public void setjButton1(JButton jButton1) {
        this.jButtonlogeo = jButton1;
    }

    //Valida que en el caso de que si no ha insertado la contraseña o el nombre o las dos nos salte un mensajito
    private void validarEntrada(BusquedasMongo buscar) {
        if (Contrasenia.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No ha insertado su contraseña");
        }
        if (Nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No ha insertado su nombre");
        } else {
            logeo(buscar);

        }
    }

    //aqui empieza la magia del logeo
    private void logeo(BusquedasMongo buscar) {
        //Nos declaramos dos cursores que los utilizaremos para buscar en cada tabla. Les mandamos el nombre y la contraseña
        DBCursor cursor = buscar.buscarUsuarioNombreContrasenia(Nombre.getText(), Contrasenia.getText());
        DBCursor cursor2 = buscar.buscarProfesorNombreContrasenia(Nombre.getText(), Contrasenia.getText());
        try {
            //Si se ha encontrado el usuario con la contraseña y el nombre entrara en esta condición. En esta zona esta buscando en la tabla alumnos
            if (cursor.size() != 0) {
                //Recorremos el cursor 
                while (cursor.hasNext()) {
                    //Nos declaramos una variable alumno y le pedimos que nos de al usuario del cursor
                    Alumnos alumno = new Alumnos((BasicDBObject) cursor.next(), 1);
                    if (alumno.getSexoAlumno().equalsIgnoreCase("hombre")) {
                        JOptionPane.showMessageDialog(this, "Bienvenido " + alumno.getNombreAlumno());
                    } else {
                        JOptionPane.showMessageDialog(this, "Bienvenida " + alumno.getNombreAlumno());
                    }

                    //Nos declaramos la ventana de los alumnos donde redirgiremos al usuarior
                    VentanaAlumno ventanaAlumno = new VentanaAlumno(this);

                    //En el caso de que el usuario sea una mujer se cambiara el avatar que se tiene por defecto
                    if (alumno.getSexoAlumno().equalsIgnoreCase("mujer")) {
                        ventanaAlumno.getSexo().setIcon(new ImageIcon(getClass().getResource("../Imagenes/icons8-alumna-48.png")));
                    }

                    //Pedimos a la ventana de los alumnos que nos de los jLabels y le mandamos tanto el codigo del alumno como su nombre
                    ventanaAlumno.getNombreAlumno().setText(alumno.getNombreAlumno());
                    ventanaAlumno.getCodAlumno().setText(alumno.getIdAlumno() + "");

                    //Hacemos la ventana principal invisible y limpiamos los campos
                    this.setVisible(false);
                    clear();
                }
            }
            //En el caso de que haya encontrado un usuario en la tabla profesores
            if (cursor2.size() != 0) {
                //Recorre el cursor
                while (cursor2.hasNext()) {

                    //Nos declaramos un objeto profesor y le mandamos el segundo cursor
                    Profesores profe = new Profesores((BasicDBObject) cursor2.next(), 1);
                    if (profe.getSexoProfesor().equalsIgnoreCase("hombre")) {
                        JOptionPane.showMessageDialog(this, "Bienvenido " + profe.getNombreProfesor(), "Mensaje de bienvenida", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Bienvenida " + profe.getNombreProfesor(), "Mensaje de bienvenida", JOptionPane.INFORMATION_MESSAGE);
                    }
                    //Si el profesor es un admin 
                    if (profe.isAdmin()) {
                        //Preguntamos si quiere entrar como admin
                        int advertencia = JOptionPane.showConfirmDialog(this, "¿Quiere entrar como admin?");

                        //En el caso de que quiera entrar como admin
                        if (advertencia == JOptionPane.YES_OPTION) {

                            VentanaAdmin ventanaAdmin = new VentanaAdmin(this);
                            //Lo mismo que con el alumno, se cambia el avatar a mujer
                            if (profe.getSexoProfesor().equalsIgnoreCase("Mujer")) {
                                ventanaAdmin.getSexo().setIcon(new ImageIcon(getClass().getResource("../Imagenes/icons8-usuario-femenino-50.png")));
                            }

                            System.out.println("Admin");

                            //Le mandamos a la siguiente ventana la información
                            ventanaAdmin.getNombreAdmin().setText(profe.getNombreProfesor().toUpperCase());
                            ventanaAdmin.getjLabel_codigo().setText("" + profe.getIdProfesor());
                            this.setVisible(false);
                            clear();
                        }
                        //En el caso de que quiera entrar como profesor
                        if (advertencia == JOptionPane.NO_OPTION) {

                            VentanaProfesor ventanaProfesor = new VentanaProfesor(this);
                            if (!profe.getSexoProfesor().equalsIgnoreCase("hombre")) {
                                ventanaProfesor.getSexo().setIcon(new ImageIcon(getClass().getResource("../Imagenes/icons8-usuario-femenino-50.png")));
                            }
                            //Le mandamos a la siguiente ventana la información
                            ventanaProfesor.getNombreProfesor().setText(profe.getNombreProfesor().toUpperCase());
                            ventanaProfesor.getjLabel_codigo().setText("" + profe.getIdProfesor());
                            this.setVisible(false);
                            clear();
                        }
                        //En el caso de que no sea admin
                    } else {

                        System.out.println("No admin");
                        System.out.println("Nombre: " + profe.getNombreProfesor());
                        VentanaProfesor ventanaProfesor = new VentanaProfesor(this);
                            if (!profe.getSexoProfesor().equalsIgnoreCase("hombre")) {
                                ventanaProfesor.getSexo().setIcon(new ImageIcon(getClass().getResource("../Imagenes/icons8-usuario-femenino-50.png")));
                            }
                       
                        //Le mandamos a la siguiente ventana la información
                        ventanaProfesor.getNombreProfesor().setText(profe.getNombreProfesor().toUpperCase());
                        ventanaProfesor.getjLabel_codigo().setText("" + profe.getIdProfesor());
                        this.setVisible(false);
                        clear();
                    }

                }
            }
            //En el caso de que no hayan encontrado a ningun usuario con esas credenciales
            if (cursor.size() == 0 && cursor2.size() == 0) {
                JOptionPane.showMessageDialog(this, "Lo siento, las credenciales no son correctas.");
                Nombre.setText("");
                Contrasenia.setText("");
            }

        } finally {
            //Una vez han terminado los cursores se cierran
            cursor.close();
            cursor2.close();

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //Cuando ejecutamos el programa, arranca con el constructor de arriba
            new VentanaDeInicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contrasenia;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Registrarse;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel cambiarContrasenia;
    private javax.swing.JButton jButtonlogeo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton visible_code;
    // End of variables declaration//GEN-END:variables
}
