/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasAdmin;

import Beans.Alumnos;
import Beans.Profesores;
import Utilidades.ConnectionMongoDB;
import Ventanas.VentanaAdmin;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBObject;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 3medi
 */
public class VentanaVisualizarPersonas extends javax.swing.JFrame {

    private ConnectionMongoDB connectionMongoDB;
    private ArrayList<Profesores> profe = new ArrayList<>();
    private ArrayList<Alumnos> alumno = new ArrayList<>();
    private BasicDBObject update, setObject;
    private VentanaAdmin ventanasAdmin;

    /**
     * Creates new form VentanaVisualizarUnaPersona
     *
     * @param ventanasAdmin
     */
    //Constructor principal que espera la ventana administrador
    public VentanaVisualizarPersonas(VentanaAdmin ventanasAdmin) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        jLabelContrasenia.setVisible(false);
        contrasenia.setVisible(false);
        this.ventanasAdmin = ventanasAdmin;
        if (ventanasAdmin.getjLabel_codigo().getText().equalsIgnoreCase(ventanasAdmin.getBusquedas().getText())) {
            Eliminar.setEnabled(false);
            jLabelContrasenia.setVisible(true);
            contrasenia.setVisible(true);
        }

    }

    //Constructor para controlar por donde entra
    private VentanaVisualizarPersonas() {
        System.out.println("Para acceder a la aplicación tiene que iniciar desde el login.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Volver = new javax.swing.JButton();
        NombreTabla = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelCambio = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        Edad = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Cambio = new javax.swing.JTextField();
        Sexo = new javax.swing.JTextField();
        Eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();
        jLabelContrasenia = new javax.swing.JLabel();
        contrasenia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        Volver.setBackground(new java.awt.Color(0, 0, 0));
        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-volver-50.png"))); // NOI18N
        Volver.setToolTipText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        NombreTabla.setFont(new java.awt.Font("Bookman Old Style", 2, 36)); // NOI18N
        NombreTabla.setForeground(new java.awt.Color(255, 255, 255));
        NombreTabla.setText("Visualizar personas");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos:");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad:");

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono:");

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo:");

        jLabelCambio.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabelCambio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCambio.setText("Curso:");

        Nombre.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N

        Apellidos.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        Edad.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        Edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EdadKeyTyped(evt);
            }
        });

        Telefono.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        Cambio.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        Sexo.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        Eliminar.setBackground(new java.awt.Color(0, 0, 0));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-papelera-vacía-50.png"))); // NOI18N
        Eliminar.setToolTipText("Eliminar usuario");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        modificar.setBackground(new java.awt.Color(0, 0, 0));
        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cambiar-50.png"))); // NOI18N
        modificar.setToolTipText("Modificar usuario");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");

        jLabel_id.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        jLabel_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_id.setText("---");

        jLabelContrasenia.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabelContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContrasenia.setText("Contraseña:");

        contrasenia.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(146, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelContrasenia)
                                .addGap(18, 18, 18)
                                .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Sexo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(Edad))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCambio, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(Apellidos)
                                    .addComponent(Cambio))))
                        .addContainerGap(79, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_id)
                .addGap(24, 24, 24)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NombreTabla)
                    .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelCambio)
                    .addComponent(Cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_id, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton confirmar salida
    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        int advertencia = JOptionPane.showConfirmDialog(null, "¿Está seguro de volver a la vista admin? Se perderán los datos modificados");

        if (advertencia == JOptionPane.YES_OPTION) {
            dispose();

        }


    }//GEN-LAST:event_VolverActionPerformed

    private void EdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdadKeyTyped
        // Validar que no pueda pulsar letras
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo pueden insertarse numeros");
        }
    }//GEN-LAST:event_EdadKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        // Validar que no pueda pulsar letras
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo pueden insertarse numeros");
        }
    }//GEN-LAST:event_TelefonoKeyTyped

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        System.out.println("borrando usuario");
        // Confirmar al eliminar a un usuario
        int advertencia = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar a " + Nombre.getText() + "?");

        if (advertencia == JOptionPane.YES_OPTION) {
            connectionMongoDB = new ConnectionMongoDB();
            DBObject finddoc = new BasicDBObject("_id", Integer.parseInt(jLabel_id.getText()));
            connectionMongoDB.getColleccion().remove(finddoc);

            DBCollection nuevaCollection = connectionMongoDB.getDb().getCollection("Profesor");
            nuevaCollection.remove(finddoc);
            connectionMongoDB.getMongo().close();
            JOptionPane.showMessageDialog(this, "Usuario eliminado.");
            dispose();
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        System.out.println("Modificando usuario");
        //Buscamos la tabla que deseamos modificar
        connectionMongoDB = new ConnectionMongoDB();
        DBCollection nuevaCollection = connectionMongoDB.getDb().getCollection("Profesor");
        DBObject find = new BasicDBObject("_id", Integer.parseInt(jLabel_id.getText()));

        //Sino a insertado algun campo salta un mensaje 
        if (Cambio.getText().equalsIgnoreCase("") || Sexo.getText().equalsIgnoreCase("") || Nombre.getText().equals("") || Apellidos.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, complete todos los campos");
        } else {
            //Si ha completado todos los campos
            int advertencia = JOptionPane.showConfirmDialog(null, "¿Esta seguro de cambiar los datos de " + Nombre.getText() + "?");

            if (advertencia == JOptionPane.YES_OPTION) {
                try {
                    if (Integer.parseInt(jLabel_id.getText()) > 100 && Integer.parseInt(jLabel_id.getText()) < 200) {
                        System.out.println("Profe");
                        if (Cambio.getText().equalsIgnoreCase("true") || Cambio.getText().equalsIgnoreCase("false")) {
                            if (Sexo.getText().equalsIgnoreCase("Hombre") || Sexo.getText().equalsIgnoreCase("Mujer")) {

                                update = new BasicDBObject();

                                update.append("nombre", Nombre.getText());
                                update.append("apellidos", Apellidos.getText());
                                update.append("edad", Integer.parseInt(Edad.getText()));
                                update.append("admin", Boolean.valueOf(Cambio.getText().toLowerCase()));
                                update.append("telefono", Integer.parseInt(Telefono.getText()));
                                update.append("sexo", Sexo.getText());

                                if (this.ventanasAdmin.getjLabel_codigo().getText().equalsIgnoreCase(jLabel_id.getText())) {
                                    System.out.println("hola");
                                    update.append("contrasenia", contrasenia.getText());
                                }

                                setObject = new BasicDBObject();
                                setObject.append("$set", update);
                                nuevaCollection.update(find, setObject);
                                dispose();
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Solo puede ser hombre o mujer");
                                Sexo.setText("");
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Solo puede ser true o false");
                            Cambio.setText("");
                        }
                    } else {
                        System.out.println("ALumno");

                        if (Sexo.getText().equalsIgnoreCase("Hombre") || Sexo.getText().equalsIgnoreCase("Mujer")) {
                            update = new BasicDBObject();

                            update.append("nombre", Nombre.getText());
                            update.append("apellidos", Apellidos.getText());
                            update.append("edad", Integer.parseInt(Edad.getText()));
                            update.append("curso", Cambio.getText());
                            update.append("telefono", Integer.parseInt(Telefono.getText()));
                            update.append("sexo", Sexo.getText());

                            setObject = new BasicDBObject();
                            setObject.append("$set", update);

                            connectionMongoDB.getColleccion().update(find, setObject);
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Solo puede ser hombre o mujer");
                        }

                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(rootPane, "Error a la hora de insertar la edad o el telefono");

                }
            }
        }
        connectionMongoDB.getMongo().close();
    }//GEN-LAST:event_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVisualizarPersonas().setVisible(true);
            }
        });
    }

    public JTextField getContrasenia() {
        return contrasenia;
    }

    public void setContrasenia(JTextField contrasenia) {
        this.contrasenia = contrasenia;
    }

    public JLabel getjLabel_id() {
        return jLabel_id;
    }

    public JTextField getApellidos() {
        return Apellidos;
    }

    public void setApellidos(JTextField Apellidos) {
        this.Apellidos = Apellidos;
    }

    public JTextField getCambio() {
        return Cambio;
    }

    public void setCambio(JTextField Cambio) {
        this.Cambio = Cambio;
    }

    public JTextField getEdad() {
        return Edad;
    }

    public void setEdad(JTextField Edad) {
        this.Edad = Edad;
    }

    public JTextField getNombre() {
        return Nombre;
    }

    public void setNombre(JTextField Nombre) {
        this.Nombre = Nombre;
    }

    public JLabel getNombreTabla() {
        return NombreTabla;
    }

    public void setNombreTabla(JLabel NombreTabla) {
        this.NombreTabla = NombreTabla;
    }

    public JTextField getTelefono() {
        return Telefono;
    }

    public void setTelefono(JTextField Telefono) {
        this.Telefono = Telefono;
    }

    public JTextField getSexo() {
        return Sexo;
    }

    public void setSexo(JTextField Sexo) {
        this.Sexo = Sexo;
    }

    public JLabel getjLabelCambio() {
        return jLabelCambio;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidos;
    private javax.swing.JTextField Cambio;
    private javax.swing.JTextField Edad;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel NombreTabla;
    private javax.swing.JTextField Sexo;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField contrasenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCambio;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
