/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasAdmin;

import Beans.Alumnos;
import Beans.Profesores;
import Utilidades.BusquedasMongo;
import Utilidades.ConnectionMongoDB;
import Utilidades.Inserts;
import Ventanas.VentanaAdmin;
import com.mongodb.DBCursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 3medi
 */
public class VentanaInsertarUsuarios extends javax.swing.JFrame {

    private ConnectionMongoDB conexion;
    private ArrayList<Profesores> profe = new ArrayList<>();
    private ArrayList<Alumnos> alumno = new ArrayList<>();
    private VentanaAdmin ventanaAdmin;
    private BusquedasMongo buscar;
    private DBCursor cursor;

    /**
     * Creates new form VentanaInsertarUsuarios
     *
     * @param ventanaAdmin
     */
    //Constructor principal que espera la ventana administrador
    public VentanaInsertarUsuarios(VentanaAdmin ventanaAdmin) {
        this.ventanaAdmin = ventanaAdmin;
        initComponents();
        setVisible(true);

        setLocationRelativeTo(null);
        Admin.setVisible(false);
    }

    //Metodo de seguridad para que no pueda ejeutar la aplicación de forma que no deseemos 
    private VentanaInsertarUsuarios() {
        System.out.println("Para acceder a la aplicación tiene que iniciar desde el login.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Apellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Contrasenia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sexo = new javax.swing.JPanel();
        Hombre = new javax.swing.JRadioButton();
        Mujer = new javax.swing.JRadioButton();
        Cambio = new javax.swing.JTextField();
        Admin = new javax.swing.JCheckBox();
        jLabelCambio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BotonAniadir = new javax.swing.JButton();
        ComoAlumnoProfe = new javax.swing.JComboBox<>();
        VolverAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inserte los usuarios");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        Nombre.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellidos");

        Apellidos.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad");

        Edad.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        Edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EdadKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");

        Telefono.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña");

        Contrasenia.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo");

        sexo.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(Hombre);
        Hombre.setSelected(true);
        Hombre.setText("Hombre");

        buttonGroup1.add(Mujer);
        Mujer.setText("Mujer");

        javax.swing.GroupLayout sexoLayout = new javax.swing.GroupLayout(sexo);
        sexo.setLayout(sexoLayout);
        sexoLayout.setHorizontalGroup(
            sexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Mujer)
                .addContainerGap())
        );
        sexoLayout.setVerticalGroup(
            sexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hombre)
                    .addComponent(Mujer))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        Cambio.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        jLabelCambio.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabelCambio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCambio.setText("Curso");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        BotonAniadir.setBackground(new java.awt.Color(0, 0, 0));
        BotonAniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-guardar-50.png"))); // NOI18N
        BotonAniadir.setToolTipText("Guardar nuevo usuario");
        BotonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAniadirActionPerformed(evt);
            }
        });

        ComoAlumnoProfe.setBackground(new java.awt.Color(204, 204, 204));
        ComoAlumnoProfe.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        ComoAlumnoProfe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Profesor" }));
        ComoAlumnoProfe.setToolTipText("Seleccione el tipo de usuario");
        ComoAlumnoProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComoAlumnoProfeActionPerformed(evt);
            }
        });

        VolverAdmin.setBackground(new java.awt.Color(0, 0, 0));
        VolverAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-volver-50.png"))); // NOI18N
        VolverAdmin.setToolTipText("Volver");
        VolverAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(VolverAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(ComoAlumnoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Admin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Apellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Edad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Telefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Contrasenia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 76, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VolverAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCambio)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComoAlumnoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdadKeyTyped
        // Controlamos que solo pueda meter números
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo pueden insertarse numeros");
        }
    }//GEN-LAST:event_EdadKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        // Controlamos que solo pueda meter números
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo pueden insertarse numeros");
        }
    }//GEN-LAST:event_TelefonoKeyTyped

    private void BotonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAniadirActionPerformed
        System.out.println("Insertando usuario");
        //Iniciamos nuestros objetos
        conexion = new ConnectionMongoDB();
        Inserts cargarDatos = new Inserts();
        //guardamos nuestros datos en nuestras variables
        String sexoU = "";
        String seleccionado = ComoAlumnoProfe.getSelectedItem().toString();
        //Si selecciona un button u otro le damos un valor determinado
        if (Hombre.isSelected()) {
            sexoU = "Hombre";

        }
        if (Mujer.isSelected()) {
            sexoU = "Mujer";

        }
        try {
            //Si selecciona alumno
            if (seleccionado.equals("Alumno")) {
                //Llamamos al metodo de insertar alumnos
                cargarDatos.insertAlumnos(cursor, buscar, alumno, conexion, Nombre.getText(), rootPane, Apellidos.getText(), Integer.parseInt(Edad.getText()), Cambio.getText(), Integer.parseInt(Telefono.getText()), sexoU, Contrasenia.getText(), Hombre);

            }
            if (seleccionado.equals("Profesor")) {
                //Llamamos al metodo de insertar profesores
                 cargarDatos.insertProfesores(conexion, buscar, cursor, profe, Nombre.getText(), Apellidos.getText(), Integer.parseInt(Edad.getText()), Admin, Integer.parseInt(Telefono.getText()), sexoU, Contrasenia.getText(), Hombre, rootPane);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Lo siento, ha dejado algun campo sin rellenar.");
            Clear();
        } catch (IllegalStateException e) {
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error con la base de datos. Por favor, rellene todos los campos para continuar");
            Clear();
        }

        Clear();
        conexion.getMongo().close();
    }//GEN-LAST:event_BotonAniadirActionPerformed

    private void ComoAlumnoProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComoAlumnoProfeActionPerformed
        // Dependiendo de si entras como alumno o profesor saldran unos datos u otros

        String seleccionado = ComoAlumnoProfe.getSelectedItem().toString();
        if (seleccionado.equals("Alumno")) {

            jLabelCambio.setText("Curso");
            Cambio.setVisible(true);
            Admin.setVisible(false);

        }
        if (seleccionado.equals("Profesor")) {

            jLabelCambio.setText("Admin");
            Cambio.setVisible(false);
            Admin.setVisible(true);
        }
    }//GEN-LAST:event_ComoAlumnoProfeActionPerformed

    private void VolverAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverAdminActionPerformed

        System.out.println("volviendo");
        //Confirmación antes de volver a la ventana anterior
        int advertencia = JOptionPane.showConfirmDialog(null, "¿Ha terminado de insertar usuarios? ");

        if (advertencia == JOptionPane.YES_OPTION) {
            dispose();
            ventanaAdmin.setVisible(true);
        }
    }//GEN-LAST:event_VolverAdminActionPerformed
    
    //Metodo para limpiar los datos en pantalla 
    private void Clear() {
        System.out.println("Limpiando campos");
        Nombre.setText("");
        Apellidos.setText("");
        Edad.setText("");
        Cambio.setText("");
        Telefono.setText("");
        Contrasenia.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInsertarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Admin;
    private javax.swing.JTextField Apellidos;
    private javax.swing.JButton BotonAniadir;
    private javax.swing.JTextField Cambio;
    private javax.swing.JComboBox<String> ComoAlumnoProfe;
    private javax.swing.JTextField Contrasenia;
    private javax.swing.JTextField Edad;
    private javax.swing.JRadioButton Hombre;
    private javax.swing.JRadioButton Mujer;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton VolverAdmin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCambio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel sexo;
    // End of variables declaration//GEN-END:variables
}
