/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasProfesor;

import Beans.Alumnos;
import Beans.FaltasAlumnos;
import Utilidades.BusquedasMongo;
import Utilidades.CargarTablas;
import Utilidades.ConnectionMongoDB;
import Ventanas.VentanaProfesor;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author 3medi
 */
public class VentanaFaltasAlumnos extends javax.swing.JFrame {

    //Nos declaramos nuestros objetos 
    private VentanaProfesor ventana;
    private Calendar fecha_actual;
    private ConnectionMongoDB conexion;
    private ArrayList<FaltasAlumnos> faltas = new ArrayList<>();
    private BusquedasMongo buscar, buscar2;
    private DBCursor cursor;
    private ConnectionMongoDB connectionMongoDB;
    private BasicDBObject update, setObject;

    /**
     * Creates new form VentanaFaltasAlumnos
     *
     * @param ventana
     */
    //Constructor principal 
    public VentanaFaltasAlumnos(VentanaProfesor ventana) {
        initComponents();
        this.setVisible(true);
        this.ventana = ventana;
        setLocationRelativeTo(null);
        fecha_actual = new GregorianCalendar();

    }

    private VentanaFaltasAlumnos() {
        System.out.println("Para acceder a la aplicación tiene que iniciar desde el login.");
    }

    public JTable getTablaVisible() {
        return TablaVisible;
    }

    public void setTablaVisible(JTable TablaVisible) {
        this.TablaVisible = TablaVisible;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        actualizarTabla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaVisible = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser_Dia = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        AlumnoID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        justificacion = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        aniadir = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        EliminarPorId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Justificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        faltaIdJustificar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Faltas alumnos");

        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 2, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        actualizarTabla.setBackground(new java.awt.Color(0, 0, 0));
        actualizarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-actualizar-35_1.png"))); // NOI18N
        actualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTablaActionPerformed(evt);
            }
        });

        TablaVisible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaVisible.setEnabled(false);
        jScrollPane2.setViewportView(TablaVisible);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(actualizarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actualizarTabla)
                .addContainerGap(369, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dia");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AlumnoID");

        AlumnoID.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Justificación");

        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        aniadir.setBackground(new java.awt.Color(0, 0, 0));
        aniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-de-acuerdo-35.png"))); // NOI18N
        aniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadirActionPerformed(evt);
            }
        });

        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        EliminarPorId.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FaltaID");

        Eliminar.setBackground(new java.awt.Color(0, 0, 0));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-eliminar-35.png"))); // NOI18N
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-desanclar-2-100.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-volver-50.png"))); // NOI18N
        jButton1.setToolTipText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Justificar.setBackground(new java.awt.Color(0, 0, 0));
        Justificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cambiar-50.png"))); // NOI18N
        Justificar.setToolTipText("Justificar");
        Justificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JustificarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FaltaID");

        faltaIdJustificar.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AlumnoID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(aniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(justificacion))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(EliminarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(faltaIdJustificar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(Justificar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(AlumnoID, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EliminarPorId, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(faltaIdJustificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(justificacion))
                        .addGap(32, 32, 32)
                        .addComponent(Justificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTablaActionPerformed

        //Botón para cargar el contenido de las tablas 
        CargarTablas cargarTablas = new CargarTablas();
        cargarTablas.cargarTablaFaltasAlumnos(this);
    }//GEN-LAST:event_actualizarTablaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Botón pra volver atras 
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadirActionPerformed

        //Inicializamos los objetos 
        conexion = new ConnectionMongoDB();
        buscar = new BusquedasMongo();
        buscar2 = new BusquedasMongo();
        try {

            //Si la fecha es anterior a la actual muestra un mensaje y borra la fecha anterior 
            if (fecha_actual.compareTo(jDateChooser_Dia.getCalendar()) == 1) {
                JOptionPane.showMessageDialog(rootPane, "La fecha no es correcta, ponga una más apropiada.");
                jDateChooser_Dia.setCalendar(null);
            }
            //Si no ha insertado ninguna fecha 
            if (jDateChooser_Dia.getCalendar() == null) {
                JOptionPane.showMessageDialog(rootPane, "No ha puesto ninguna fecha.");
            }
            //Si no ha insertado ningún alumno 
            if (AlumnoID.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(rootPane, "No ha puesto al alumno.");
            } else {

                //Sacamos la collection que deseamos
                DBCollection nuevaCollection = conexion.getDb().getCollection("FaltasAlumno");

                int numDocumentos = 1;
                //Hacemos las busquedas y las guardamos en los cursores
                cursor = buscar.buscarPorCodigo(numDocumentos, "FaltasAlumno");
                DBCursor cursor2 = buscar2.buscarUsuarioCodigo(Integer.parseInt(AlumnoID.getText()));

                //Damos formato a la fecha
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                String date = format.format(jDateChooser_Dia.getDate());

                //Si encuentra al usuario
                if (cursor2.size() != 0) {
                    while (cursor2.hasNext()) {
                        Alumnos alum = new Alumnos((BasicDBObject) cursor2.next());
                        //Mientras encuentre al usuario irá sumando uno hasta que no lo encuentre
                        while (cursor.size() == 1) {
                            numDocumentos = numDocumentos + 1;
                            cursor = buscar.buscarPorCodigo(numDocumentos, "FaltasAlumno");
                        }

                        //Añadimos la falta al array
                        faltas.add(new FaltasAlumnos(numDocumentos, date, false, Integer.parseInt(AlumnoID.getText()), alum.getNombreAlumno()));
                        //Añadimos la falta a la nueva collection
                        for (FaltasAlumnos faltasT : faltas) {
                            nuevaCollection.insert(faltasT.toDBObjectsFaltasAlumnos());
                        }
                        JOptionPane.showMessageDialog(rootPane, "Se añadió satisfactoriamente.");
                    }
                    //En el caso de que no encuentre al alumno
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Alumno no encontrado.");
                }
                //Cerramos el cursor
                cursor.close();

                jDateChooser_Dia.setCalendar(null);
                AlumnoID.setText("");
            }

            //Controlamos las excepciones
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, "Lo siento, no ha puesto la fecha.");

        } catch (IllegalStateException e) {
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error con la base de datos. Por favor, rellene todos los campos para continuar");

        }

        //Cerramos la conexión 
        conexion.getMongo().close();
    }//GEN-LAST:event_aniadirActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

        //Inicializamos las busquedas
        buscar = new BusquedasMongo();

        //Preguntamos si esta seguro de borrar la falta
        int advertencia = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la falta con la id " + EliminarPorId.getText() + "?");

        //Si esta seguro 
        if (advertencia == JOptionPane.YES_OPTION) {
            //Si esta vacio la id
            if (EliminarPorId.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "No ha insertado la id, por favor vuelva a intentarlo.");
            } else {
                //Damos valor a nuestro cursor 
                cursor = buscar.buscarPorCodigo(Integer.parseInt(EliminarPorId.getText()), "FaltasAlumno");

                //Si encuentra al usuario
                if (cursor.size() == 1) {

                    //Inicializamos la conexión 
                    connectionMongoDB = new ConnectionMongoDB();
                    //Decimos a quien buscamos
                    DBObject finddoc = new BasicDBObject("_id", Integer.parseInt(EliminarPorId.getText()));

                    connectionMongoDB.getColleccion().remove(finddoc);
                    //Sacamos la collection
                    DBCollection nuevaCollection = connectionMongoDB.getDb().getCollection("FaltasAlumno");

                    //Borramos de la conexión al usuario
                    nuevaCollection.remove(finddoc);
                    JOptionPane.showMessageDialog(rootPane, "Se borró satisfactoriamente.");
                    EliminarPorId.setText("");
                    //Cerramos la conexión
                    connectionMongoDB.getMongo().close();

                } else {
                    //Si no encuentra a nadie muestra el mensaje
                    JOptionPane.showMessageDialog(rootPane, "No se encontro ninguna falta asociado a este profesor.");
                    EliminarPorId.setText("");
                }
                cursor.close();
                dispose();
            }
        }

    }//GEN-LAST:event_EliminarActionPerformed

    private void JustificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JustificarActionPerformed

        //Inicializamos la conexion y buscamos la collection
        connectionMongoDB = new ConnectionMongoDB();
        DBCollection nuevaCollection = connectionMongoDB.getDb().getCollection("FaltasAlumno");

        //Si no ha insertado la id de la falta muestra un mensaje
        if (faltaIdJustificar.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, inserte la id");
        } else {
            //Declaramos un objeto con la id 
            DBObject find = new BasicDBObject("_id", Integer.parseInt(faltaIdJustificar.getText()));

            //Preguntamos si está seguro de justificar la falta
            int advertencia = JOptionPane.showConfirmDialog(null, "¿Esta seguro de justificar la falta con id: " + faltaIdJustificar.getText() + "?");

            //Si está seguro 
            if (advertencia == JOptionPane.YES_OPTION) {
                //Inicializamos el update
                update = new BasicDBObject();

                //damos valor al update
                update.append("justificada", justificacion.isSelected());
                //Nos creamos un objeto que sea nuestra condición
                setObject = new BasicDBObject();
                setObject.append("$set", update);

                //Si esta seleccionado para justificar 
                if (justificacion.isSelected()) {
                    //Modificamos los datos en la collection
                    nuevaCollection.update(find, setObject);
                    
                    JOptionPane.showMessageDialog(rootPane, "Falta justificada.");
                    justificacion.setSelected(false);
                    faltaIdJustificar.setText("");
                } else {
                    //Si no esta seleccionado muestra un mensaje 
                    JOptionPane.showMessageDialog(rootPane, "No se ha justificado la falta.");
                    justificacion.setSelected(false);
                    faltaIdJustificar.setText("");
                }
            }
        }

    }//GEN-LAST:event_JustificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFaltasAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFaltasAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFaltasAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFaltasAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFaltasAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlumnoID;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField EliminarPorId;
    private javax.swing.JButton Justificar;
    private javax.swing.JTable TablaVisible;
    private javax.swing.JButton actualizarTabla;
    private javax.swing.JButton aniadir;
    private javax.swing.JTextField faltaIdJustificar;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser_Dia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox justificacion;
    // End of variables declaration//GEN-END:variables
}
