/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasProfesor;

import Utilidades.CargarDatos;
import Utilidades.Cliente;
import Utilidades.Servidor;
import com.sun.glass.events.KeyEvent;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author 3medi
 */
public class VentanaChatProfesor extends javax.swing.JFrame implements Observer {

    private Ventanas.VentanaProfesor profesor;
    private Thread thread;
    private Thread tCliente;

    /**
     * Creates new form VentanaServidor
     *
     * @param profesor
     */
    //Constructor principal que recibe la ventana del profesor 
    public VentanaChatProfesor(Ventanas.VentanaProfesor profesor) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);

        this.profesor = profesor;
        this.getRootPane().setDefaultButton(this.Enviar);

        //Iniciamos el hilo del servidor
        Servidor servidor = new Servidor(5000, this, Conectado);
        servidor.addObserver(this);
        thread = new Thread(servidor);
        thread.start();

        //Cargamos los datos del fichero txt en el panel
        CargarDatos cargarDatos = new CargarDatos();
        cargarDatos.leerTxt(panelChat);
    }

    private VentanaChatProfesor() {
        System.out.println("Para acceder a la aplicación tiene que iniciar desde el login.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelChat = new javax.swing.JTextArea();
        textoEnviar = new javax.swing.JTextField();
        volver = new javax.swing.JButton();
        Enviar = new javax.swing.JButton();
        Conectado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        panelChat.setColumns(20);
        panelChat.setRows(5);
        panelChat.setFocusable(false);
        jScrollPane1.setViewportView(panelChat);

        textoEnviar.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-volver-50.png"))); // NOI18N
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        Enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-enviar-40.png"))); // NOI18N
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        Conectado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-desconectado-30.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Conectado)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Enviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoEnviar))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Conectado)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        //Botón para volver a la ventana anterior 
        this.dispose();
        
        //Si el usuario sale se guardan en un txt el archo 
        Utilidades.CargarDatos cargarDatos = new CargarDatos();
        cargarDatos.escribirArchivo(panelChat.getText());
    }//GEN-LAST:event_volverActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed

        String mensaje = profesor.getNombreProfesor().getText() + ": " + this.textoEnviar.getText() + "\n";

        this.panelChat.append(mensaje);
        //Iniciamos el hilo del cliente 
        Cliente cliente = new Cliente(6000, mensaje, this, panelChat, Conectado);
        tCliente = new Thread(cliente);
        tCliente.start();

        this.textoEnviar.setText("");
    }//GEN-LAST:event_EnviarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // Lo mismo que el botón pero con la tecla enter 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String mensaje = profesor.getNombreProfesor().getText() + ": " + this.textoEnviar.getText() + "\n";

            this.panelChat.append(mensaje);

            Cliente cliente = new Cliente(6000, mensaje, this, panelChat, Conectado);
            Thread t = new Thread(cliente);
            t.start();

            this.textoEnviar.setText("");
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaChatProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaChatProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaChatProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaChatProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaChatProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Conectado;
    private javax.swing.JButton Enviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea panelChat;
    private javax.swing.JTextField textoEnviar;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        this.panelChat.append((String) o1);
    }
}
