/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasProfesor;

import Utilidades.CargarTablas;
import Ventanas.VentanaGraficarAlumno;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author 3medi
 */
public class VentanaVisualizarAlumno extends javax.swing.JFrame {

    private int codigo;
    private int codProfesor;

    /**
     * Creates new form VentanaVisualizarAlumno
     *
     * @param codigo
     * @param codProfesor
     */

    //Creamos un constructor que pide el codigo del profesor y del alumno 
    public VentanaVisualizarAlumno(int codigo, int codProfesor) {
        initComponents();
        this.setVisible(true);
        this.codigo = codigo;
        this.codProfesor = codProfesor;
        setLocationRelativeTo(null);
        idAlumno.setText("ID: " + this.codigo);
        Graficar.setEnabled(false);
    }

    private VentanaVisualizarAlumno() {
        System.out.println("Para acceder a la aplicación tiene que iniciar desde el login.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        SelectDatos = new javax.swing.JComboBox<>();
        Graficar = new javax.swing.JButton();
        CargarTabla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaVisible = new javax.swing.JTable();
        rendimientoAlumno = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        idAlumno = new javax.swing.JLabel();
        nombreAlumno = new javax.swing.JLabel();
        Radio3D = new javax.swing.JRadioButton();
        Radio3d = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        SelectDatos.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        SelectDatos.setForeground(new java.awt.Color(255, 255, 255));
        SelectDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asignatura", "Faltas" }));

        Graficar.setBackground(new java.awt.Color(0, 0, 0));
        Graficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-gráfico-de-barras-40.png"))); // NOI18N
        Graficar.setToolTipText("Cargar gráfico");
        Graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficarActionPerformed(evt);
            }
        });

        CargarTabla.setBackground(new java.awt.Color(0, 0, 0));
        CargarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-tabla-40.png"))); // NOI18N
        CargarTabla.setToolTipText("Cargar tabla");
        CargarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarTablaActionPerformed(evt);
            }
        });

        TablaVisible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaVisible.setEnabled(false);
        jScrollPane2.setViewportView(TablaVisible);

        rendimientoAlumno.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        rendimientoAlumno.setForeground(new java.awt.Color(255, 255, 255));
        rendimientoAlumno.setText("Rendimiento del alumno");

        botonVolver.setBackground(new java.awt.Color(0, 0, 0));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-volver-50.png"))); // NOI18N
        botonVolver.setToolTipText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        idAlumno.setFont(new java.awt.Font("Baskerville Old Face", 2, 14)); // NOI18N
        idAlumno.setForeground(new java.awt.Color(255, 255, 255));
        idAlumno.setText("ID:Alumno");

        nombreAlumno.setFont(new java.awt.Font("Baskerville Old Face", 2, 24)); // NOI18N
        nombreAlumno.setForeground(new java.awt.Color(255, 255, 255));
        nombreAlumno.setText("Nombre");

        Radio3D.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(Radio3D);
        Radio3D.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        Radio3D.setForeground(new java.awt.Color(255, 255, 255));
        Radio3D.setSelected(true);
        Radio3D.setText("3d");
        Radio3D.setToolTipText("Modelo garfica 3D");

        buttonGroup1.add(Radio3d);
        Radio3d.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        Radio3d.setForeground(new java.awt.Color(255, 255, 255));
        Radio3d.setText("2d");
        Radio3d.setToolTipText("Modelo grafica 2D");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(SelectDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(Radio3D)
                                .addGap(65, 65, 65)
                                .addComponent(Radio3d, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rendimientoAlumno)
                                .addGap(182, 182, 182))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(CargarTabla)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(Graficar)
                        .addGap(143, 143, 143))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rendimientoAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio3D, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Radio3d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Graficar)
                        .addComponent(CargarTabla))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(idAlumno)))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficarActionPerformed

        //Damos paso a la ventana graficar a la que le mandaremos los datos 
        VentanaGraficarAlumno ventanaGraficar = new VentanaGraficarAlumno(this);

        //Mandamos los valores a la ventana graficar 
        DefaultCategoryDataset barChartDataset = new DefaultCategoryDataset();
        for (int i = 0; i < TablaVisible.getRowCount(); i++) {
            barChartDataset.setValue(Integer.parseInt(TablaVisible.getValueAt(i, 1).toString()), TablaVisible.getValueAt(i, 2).toString(), TablaVisible.getValueAt(i, 0).toString());
        }
        
        if (Radio3D.isSelected()) {

            //Generará la gráfica en 3D
            JFreeChart barChart = ChartFactory.createBarChart3D("Grafica de " + nombreAlumno.getText(), "Fechas", "Notas", barChartDataset, PlotOrientation.VERTICAL, true, true, false);
            CategoryPlot bPlot = barChart.getCategoryPlot();
            bPlot.setRangeGridlinePaint(Color.ORANGE);

            ChartPanel baPanel = new ChartPanel(barChart);
            baPanel.setBounds(500, 40, 500, 400);
            ventanaGraficar.getjPanel1().removeAll();
            ventanaGraficar.getjPanel1().add(baPanel, BorderLayout.CENTER);
            ventanaGraficar.getjPanel1().validate();
        } else {
            //Generará la gráfica en 2D
            JFreeChart barChart = ChartFactory.createBarChart("Grafica de " + nombreAlumno.getText(), "Fechas", "Notas", barChartDataset, PlotOrientation.VERTICAL, true, true, false);
            CategoryPlot bPlot = barChart.getCategoryPlot();
            bPlot.setRangeGridlinePaint(Color.ORANGE);

            ChartPanel baPanel = new ChartPanel(barChart);
            baPanel.setBounds(500, 40, 500, 400);
            ventanaGraficar.getjPanel1().removeAll();
            ventanaGraficar.getjPanel1().add(baPanel, BorderLayout.CENTER);
            ventanaGraficar.getjPanel1().validate();
        }

        this.setVisible(false);

    }//GEN-LAST:event_GraficarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed

        //Volver a la pestaña anterior 
        dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void CargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarTablaActionPerformed

        //Inicializamos el objeto cargar tablas 
        CargarTablas cargarTablas = new CargarTablas();
        
        int op = SelectDatos.getSelectedIndex();
        System.out.println(op);
        //Dependiendo de la opción que elijamos 
        switch (op) {
            case 0:
                
                //Cargamos los datos de las asignaturas 
                cargarTablas.cargarTablaAlumnosPorAsignatura(codigo, this,codProfesor);
                break;

            case 1:
                
                //Cargamos los datoss de las faltas 
                cargarTablas.cargarTablaAlumnosPorFaltas(codigo, this); 
                break;
        }


    }//GEN-LAST:event_CargarTablaActionPerformed

    public JButton getGraficar() {
        return Graficar;
    }

    public void setGraficar(JButton Graficar) {
        this.Graficar = Graficar;
    }

    public JTable getTablaVisible() {
        return TablaVisible;
    }

    public void setTablaVisible(JTable TablaVisible) {
        this.TablaVisible = TablaVisible;
    }

    public JLabel getNombreAlumno() {
        return nombreAlumno;
    }

    public void setNombreAlumno(JLabel nombreAlumno) {
        this.nombreAlumno = nombreAlumno;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVisualizarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVisualizarAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarTabla;
    private javax.swing.JButton Graficar;
    private javax.swing.JRadioButton Radio3D;
    private javax.swing.JRadioButton Radio3d;
    private javax.swing.JComboBox<String> SelectDatos;
    private javax.swing.JTable TablaVisible;
    private javax.swing.JButton botonVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel idAlumno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombreAlumno;
    private javax.swing.JLabel rendimientoAlumno;
    // End of variables declaration//GEN-END:variables
}
