/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Principal.VentanaDeInicio;
import Beans.Alumnos;
import Beans.Profesores;
import Utilidades.BusquedasMongo;
import Utilidades.ConnectionMongoDB;
import Utilidades.Inserts;
import com.mongodb.DBCursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 3medi
 */
public class VentanaRegistrarse extends javax.swing.JFrame {

    private VentanaDeInicio ventanaLogeo;

    private ConnectionMongoDB conexion;
    private BusquedasMongo buscar;
    private DBCursor cursor;
    private ArrayList<Profesores> profe = new ArrayList<>();
    private ArrayList<Alumnos> alumno = new ArrayList<>();

    /**
     * Creates new form VentanaRegistrarse
     *
     * @param ventanaLogeo
     */
    //Constructor principal que espera la ventana de logeo
    public VentanaRegistrarse(VentanaDeInicio ventanaLogeo) {
        this.ventanaLogeo = ventanaLogeo;
        initComponents();
        setVisible(true);
        conexion = new ConnectionMongoDB();
        setLocationRelativeTo(null);
        Admin.setVisible(false);
    }

    //Constructor que impide que se ejecute de una forma no deseada nuestra aplicación
    private VentanaRegistrarse() {
        System.out.println("Para acceder a la aplicación necesita iniciar desde el login.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        VolverLogin = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        Edad = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Cambio = new javax.swing.JTextField();
        Contrasenia = new javax.swing.JTextField();
        sexo = new javax.swing.JPanel();
        Hombre = new javax.swing.JRadioButton();
        Mujer = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelCambio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ComoAlumnoProfe = new javax.swing.JComboBox<>();
        BotonAniadir = new javax.swing.JButton();
        Admin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));

        VolverLogin.setBackground(new java.awt.Color(0, 0, 0));
        VolverLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-volver-50.png"))); // NOI18N
        VolverLogin.setToolTipText("Volver");
        VolverLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverLoginActionPerformed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        Apellidos.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        Edad.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        Edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EdadKeyTyped(evt);
            }
        });

        Telefono.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        Cambio.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        Contrasenia.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N

        sexo.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(Hombre);
        Hombre.setSelected(true);
        Hombre.setText("Hombre");

        buttonGroup1.add(Mujer);
        Mujer.setText("Mujer");

        javax.swing.GroupLayout sexoLayout = new javax.swing.GroupLayout(sexo);
        sexo.setLayout(sexoLayout);
        sexoLayout.setHorizontalGroup(
            sexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(Mujer)
                .addContainerGap())
        );
        sexoLayout.setVerticalGroup(
            sexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hombre)
                    .addComponent(Mujer))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad");

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña");

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo");

        jLabelCambio.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabelCambio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCambio.setText("Curso");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registrarse");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        ComoAlumnoProfe.setBackground(new java.awt.Color(204, 204, 204));
        ComoAlumnoProfe.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        ComoAlumnoProfe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Profesor" }));
        ComoAlumnoProfe.setToolTipText("Seleccione el tipo de usuario que es");
        ComoAlumnoProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComoAlumnoProfeActionPerformed(evt);
            }
        });

        BotonAniadir.setBackground(new java.awt.Color(0, 0, 0));
        BotonAniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-añadir-usuario-masculino-64.png"))); // NOI18N
        BotonAniadir.setToolTipText("Registrarse como profesor o alumno");
        BotonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAniadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(VolverLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Admin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelCambio)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Apellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Edad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Telefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Contrasenia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cambio))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ComoAlumnoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VolverLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(ComoAlumnoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCambio)))
                .addGap(18, 18, 18)
                .addComponent(BotonAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdadKeyTyped
        //Metodo para impedir que meta letras en la edad
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo pueden insertarse numeros");
        }
    }//GEN-LAST:event_EdadKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        //Metodo para evitar que meta letras en el telefono
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo pueden insertarse numeros");
        }
    }//GEN-LAST:event_TelefonoKeyTyped

    private void VolverLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverLoginActionPerformed

        //Boton de confirmación para volver al menú de login 
        int advertencia = JOptionPane.showConfirmDialog(null, "¿Está seguro de volver al login? Se perderán los datos");

        if (advertencia == JOptionPane.YES_OPTION) {
            dispose();
            ventanaLogeo.setVisible(true);
        }
    }//GEN-LAST:event_VolverLoginActionPerformed

    private void BotonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAniadirActionPerformed

        String sexoU = "";
        Inserts cargarDatos = new Inserts();
        //Guardamos la información del comboBox
        String seleccionado = ComoAlumnoProfe.getSelectedItem().toString();

        //Asignamos a la variable el valor de los check box
        if (Hombre.isSelected()) {
            sexoU = "Hombre";

        }
        if (Mujer.isSelected()) {
            sexoU = "Mujer";

        }
        try {
            //Si selecciona alumno
            if (seleccionado.equals("Alumno")) {
                cargarDatos.insertAlumnos(cursor, buscar, alumno, conexion, Nombre.getText(), rootPane, Apellidos.getText(), Integer.parseInt(Edad.getText()), Cambio.getText(), Integer.parseInt(Telefono.getText()), sexoU, Contrasenia.getText(), Hombre);

                dispose();
                ventanaLogeo.setVisible(true);

            }
            //En el caso de que se quiera registrar como profesor
            if (seleccionado.equals("Profesor")) {
                
                cargarDatos.insertProfesores(conexion, buscar, cursor, profe, Nombre.getText(), Apellidos.getText(), Integer.parseInt(Edad.getText()), Admin, Integer.parseInt(Telefono.getText()), sexoU, Contrasenia.getText(), Hombre, rootPane);
                dispose();
                
                ventanaLogeo.setVisible(true);
            }
            //Controlamos las excepciones
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Lo siento, ha dejado algun campo sin rellenar.");
            Clear();
        } catch (IllegalStateException e) {
            JOptionPane.showMessageDialog(rootPane, "Se ha producido un error con la base de datos. Por favor, rellene todos los campos para continuar");
            Clear();
        }

        Clear();
        conexion.getMongo().close();

    }//GEN-LAST:event_BotonAniadirActionPerformed

    private void ComoAlumnoProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComoAlumnoProfeActionPerformed
        
        //Es un metodo que cuando vayamos a seleccionar como nos vamos a registrar se visualice unos datos u otros
         String seleccionado = ComoAlumnoProfe.getSelectedItem().toString();
        if (seleccionado.equals("Alumno")) {

            jLabelCambio.setText("Curso");
            Cambio.setVisible(true);
            Admin.setVisible(false);

        }
        if (seleccionado.equals("Profesor")) {

            jLabelCambio.setText("Admin");
            Cambio.setVisible(false);
            Admin.setVisible(true);
        }
    }//GEN-LAST:event_ComoAlumnoProfeActionPerformed

    //Metodo para limpiar los campos de texto
    public void Clear() {
        Nombre.setText("");
        Apellidos.setText("");
        Edad.setText("");
        Cambio.setText("");
        Telefono.setText("");
        Contrasenia.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Admin;
    private javax.swing.JTextField Apellidos;
    private javax.swing.JButton BotonAniadir;
    private javax.swing.JTextField Cambio;
    private javax.swing.JComboBox<String> ComoAlumnoProfe;
    private javax.swing.JTextField Contrasenia;
    private javax.swing.JTextField Edad;
    private javax.swing.JRadioButton Hombre;
    private javax.swing.JRadioButton Mujer;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton VolverLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCambio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel sexo;
    // End of variables declaration//GEN-END:variables
}
