package Ventanas;

import Principal.VentanaDeInicio;
import Beans.Alumnos;
import Beans.Profesores;
import Utilidades.BusquedasMongo;
import Utilidades.CargarDatos;
import Utilidades.CargarTablas;
import VentanasAdmin.VentanaInsertarUsuarios;
import VentanasAdmin.VentanaVisualizarPersonas;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author 3medi
 */
public class VentanaAdmin extends javax.swing.JFrame {

    private VentanaDeInicio ventanaDeInicio;
    private BusquedasMongo buscar;
    private DBCursor cursor, cursor2;
    private VentanaVisualizarPersonas ventanaVisualizarPersonas;
    private VentanaInsertarUsuarios ventanaInsertar;

    /**
     * Creates new form VenatanaAdmin
     *
     * @param ventanaDeInicio
     */
    //Creamos una constructora que reciba un número para que cuando llamemos este constructor en otra zona se inicie este
    public VentanaAdmin(VentanaDeInicio ventanaDeInicio) {
        initComponents();
        this.setVisible(true);
        setLocationRelativeTo(null);
        this.ventanaDeInicio = ventanaDeInicio;

    }

    //Creamos un constructor vacio para que inicie desde este cuando quiera arrancar esta ventana (metodo de seguridad para que no pueda pasar)
    private VentanaAdmin() {
        System.out.println("Para acceder a la aplicación necesita iniciar desde el login.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Busquedas = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        nombreAdmin = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_codigo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        VolverLogeo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotonProfesor = new javax.swing.JButton();
        BotonAlumno = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Insertar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        AjustesTablas = new javax.swing.JButton();
        NombreTabla = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaVisible = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        Busquedas.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N
        Busquedas.setToolTipText("Introduzca la id deseada");
        Busquedas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusquedasKeyTyped(evt);
            }
        });

        jButtonBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-acercar-20.png"))); // NOI18N
        jButtonBuscar.setToolTipText("Buscar usuario por id");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        nombreAdmin.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        nombreAdmin.setText(" Admin");

        sexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-50.png"))); // NOI18N
        sexo.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel8.setText("Usuario por id");

        jLabel_codigo.setFont(new java.awt.Font("Baskerville Old Face", 2, 14)); // NOI18N
        jLabel_codigo.setText("codigo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Busquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Busquedas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nombreAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addComponent(jLabel_codigo)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 0, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        VolverLogeo.setBackground(new java.awt.Color(0, 0, 0));
        VolverLogeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-volver-50.png"))); // NOI18N
        VolverLogeo.setToolTipText("Volver");
        VolverLogeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverLogeoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Controles Admin");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tablas");

        BotonProfesor.setBackground(new java.awt.Color(0, 0, 0));
        BotonProfesor.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        BotonProfesor.setForeground(new java.awt.Color(255, 255, 255));
        BotonProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-formación-40.png"))); // NOI18N
        BotonProfesor.setText("Profesores");
        BotonProfesor.setToolTipText("Información de la tabla profesores");
        BotonProfesor.setHideActionText(true);
        BotonProfesor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonProfesor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotonProfesor.setIconTextGap(25);
        BotonProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProfesorActionPerformed(evt);
            }
        });

        BotonAlumno.setBackground(new java.awt.Color(0, 0, 0));
        BotonAlumno.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        BotonAlumno.setForeground(new java.awt.Color(255, 255, 255));
        BotonAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-gorro-de-graduación-40.png"))); // NOI18N
        BotonAlumno.setText("Alumnos");
        BotonAlumno.setToolTipText("Informacion tabla alumno");
        BotonAlumno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotonAlumno.setIconTextGap(25);
        BotonAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlumnoActionPerformed(evt);
            }
        });

        jPanel13.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Acciones tablas");

        Insertar.setBackground(new java.awt.Color(0, 0, 0));
        Insertar.setFont(new java.awt.Font("Baskerville Old Face", 2, 24)); // NOI18N
        Insertar.setForeground(new java.awt.Color(255, 255, 255));
        Insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-añadir-usuario-grupo-mujer-hombre-40.png"))); // NOI18N
        Insertar.setText("Usuarios");
        Insertar.setToolTipText("Menú de insertar usuarios");
        Insertar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Insertar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Insertar.setIconTextGap(25);
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        AjustesTablas.setBackground(new java.awt.Color(0, 0, 0));
        AjustesTablas.setFont(new java.awt.Font("Baskerville Old Face", 2, 24)); // NOI18N
        AjustesTablas.setForeground(new java.awt.Color(255, 255, 255));
        AjustesTablas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-ajustes-40.png"))); // NOI18N
        AjustesTablas.setText("Ajustes");
        AjustesTablas.setToolTipText("Menú de insertar usuarios");
        AjustesTablas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AjustesTablas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AjustesTablas.setIconTextGap(25);
        AjustesTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjustesTablasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(VolverLogeo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(BotonProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotonAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Insertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AjustesTablas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonProfesor)
                .addGap(26, 26, 26)
                .addComponent(BotonAlumno)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(Insertar)
                .addGap(26, 26, 26)
                .addComponent(AjustesTablas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VolverLogeo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        NombreTabla.setFont(new java.awt.Font("Bookman Old Style", 2, 36)); // NOI18N
        NombreTabla.setForeground(new java.awt.Color(255, 255, 255));
        NombreTabla.setText("Menú de tablas");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        TablaVisible.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N
        TablaVisible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaVisible);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NombreTabla)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NombreTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscar = new BusquedasMongo();

        //En el caso de que el campo de texto este vacio salta un mensaje
        if (Busquedas.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No ha insertado la id a buscar");
        } else {

            try {
                //Llamamos los doscursores que habiamos declarado al principio y le mandamos la información
                cursor = buscar.buscarUsuarioId(Integer.parseInt(Busquedas.getText()));
                cursor2 = buscar.buscarProfesorId(Integer.parseInt(Busquedas.getText()));

                //Si se encuentra al alumno
                if (cursor.size() != 0 && cursor2.size() == 0) {
                    try {
                        //Recorremos l cursor
                        while (cursor.hasNext()) {
                            System.out.println("Alumno encontrado");
                            //Nos declaramos un alumno y le mandamos la información de que alumno queremos
                            Alumnos alumno = new Alumnos((BasicDBObject) cursor.next());
                            ventanaVisualizarPersonas = new VentanaVisualizarPersonas(this);
                            //Cargamos los datos de los alumnos en los distintos campos de texto
                            CargarDatos cargarDatos = new CargarDatos();
                            cargarDatos.cargarAlumnoId(buscar.buscarUsuarioId(Integer.parseInt(Busquedas.getText())), ventanaVisualizarPersonas);
                            Busquedas.setText("");
                        }
                    } catch (NullPointerException e) {

                    }
                }
                //Si se encuentra al profesor
                if (cursor2.size() != 0 && cursor.size() == 0) {

                    //Recorre nuestro cursor
                    while (cursor2.hasNext()) {
                        System.out.println("Profe encontrado");
                        //Nos declaramos un profesor y la ventana a la cual le vamos a cambiar un label
                        Profesores profe = new Profesores((BasicDBObject) cursor2.next());
                        ventanaVisualizarPersonas = new VentanaVisualizarPersonas(this);
                        ventanaVisualizarPersonas.getjLabelCambio().setText("Admin:");

                        //Cargamos los datos en los campos de textos 
                        CargarDatos cargarDatos = new CargarDatos();
                        cargarDatos.cargarProfesoresId(buscar.buscarProfesorId(Integer.parseInt(Busquedas.getText())), ventanaVisualizarPersonas);
                        Busquedas.setText("");
                    }
                }
                //En el caso de que no se encuentre salta un mensaje y se limpia las busquedas
                if (cursor.size() == 0 && cursor2.size() == 0) {
                    System.out.println("No hay nadie con esa id");
                    JOptionPane.showMessageDialog(this, "No se ha encontrado al usuario con el codigo  " + Busquedas.getText());
                    Busquedas.setText("");

                }
                cursor.close();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, inserte solo números");
                Busquedas.setText("");
            }

        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        System.out.println("Redirigiendo a ventana insertar");
        //Llamamos a la ventana insertar
        ventanaInsertar = new VentanaInsertarUsuarios(this);

    }//GEN-LAST:event_InsertarActionPerformed

    private void BotonAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlumnoActionPerformed
        // Llamamos al metodo de cargar las tablas de los alumnos
        System.out.println("Cargando tabla Alumnos");
        NombreTabla.setText("Tabla ALUMNOS");
        CargarTablas cargarTablas = new CargarTablas();
        cargarTablas.cargarTablaAlumnos(TablaVisible);
    }//GEN-LAST:event_BotonAlumnoActionPerformed

    private void BotonProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProfesorActionPerformed
        // Llamamos al metodo de cargar tabla profesores
        System.out.println("Cargando tabla profesores");
        NombreTabla.setText("Tabla PROFESORES");
        CargarTablas cargarTablas = new CargarTablas();
        cargarTablas.cargarTablaProfesores(this);
    }//GEN-LAST:event_BotonProfesorActionPerformed

    private void VolverLogeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverLogeoActionPerformed

        //Volvemos a la ventana de logeo, en el caso de que haya alguna ventana asociada a esta abierta se cierra
        int advertencia = JOptionPane.showConfirmDialog(null, "¿Está seguro de volver al login? Se perderán los datos");

        if (advertencia == JOptionPane.YES_OPTION) {
            dispose();
            if (ventanaVisualizarPersonas != null) {
                System.out.println("Cerrando ventana visualizar personas");
                ventanaVisualizarPersonas.dispose();
            }
            if (ventanaInsertar != null) {
                System.out.println("Cerramos las inserciones.");
                ventanaInsertar.dispose();
            }

            ventanaDeInicio.setVisible(true);
            System.out.println("saliendo de admin");
        }
    }//GEN-LAST:event_VolverLogeoActionPerformed

    private void AjustesTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjustesTablasActionPerformed
        //Se desplegara un menu de ajustes de temas para personalizar la tabla 
        String[] options = {"Tema oscuro", "Tema claro", "Formato Tablas"};
        int seleccion = JOptionPane.showOptionDialog(null, "Seleccione la opción que desee.", "Ajustes", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        //La primera opción es de poner el tema oscuro
        if (seleccion == 0) {
            TablaVisible.setBackground(Color.BLACK);
            TablaVisible.setForeground(Color.WHITE);
            JOptionPane.showMessageDialog(this, "Tema oscuro aplicado a la tabla.");
            System.out.println("Tema oscuro");
        }
        //La segunda opción pone el formato de la tabla en claro
        if (seleccion == 1) {
            TablaVisible.setBackground(Color.WHITE);
            TablaVisible.setForeground(Color.BLACK);
            JOptionPane.showMessageDialog(this, "Tema claro aplicado a la tabla.");
            System.out.println("Tema claro");
        }
        //La tercera opción te permite cambiar el formato de la letra 
        if (seleccion == 2) {
            try {
                String formato = JOptionPane.showInputDialog("Inserte el tipo de letra que quiere.");
                if (formato.equalsIgnoreCase("")) {
                    JOptionPane.showMessageDialog(this, "Se quedara el formato de letra predefinido");
                }
                TablaVisible.setFont(new java.awt.Font(formato, 0, 14));
                System.out.println("Modificando tipo de letra");
            } catch (NullPointerException w) {
                JOptionPane.showMessageDialog(this, "Se quedara el formato de letra predefinido");
            }
        }
    }//GEN-LAST:event_AjustesTablasActionPerformed

    private void BusquedasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusquedasKeyTyped
        //Metodo para impedir que meta letras en la edad
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo pueden insertarse numeros");
        }
    }//GEN-LAST:event_BusquedasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }
    //Zona de gets and sets

    public JTable getTablaVisible() {
        return TablaVisible;
    }

    public void setTablaVisible(JTable TablaVisible) {
        this.TablaVisible = TablaVisible;
    }

    public JLabel getNombreAdmin() {
        return nombreAdmin;
    }

    public void setNombreAdmin(JLabel nombreAdmin) {
        this.nombreAdmin = nombreAdmin;
    }

    public JLabel getSexo() {
        return sexo;
    }

    public void setSexo(JLabel sexo) {
        this.sexo = sexo;
    }

    public JLabel getjLabel_codigo() {
        return jLabel_codigo;
    }

    public void setjLabel_codigo(JLabel jLabel_codigo) {
        this.jLabel_codigo = jLabel_codigo;
    }

    public JTextField getBusquedas() {
        return Busquedas;
    }

    public void setBusquedas(JTextField Busquedas) {
        this.Busquedas = Busquedas;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjustesTablas;
    private javax.swing.JButton BotonAlumno;
    private javax.swing.JButton BotonProfesor;
    private javax.swing.JTextField Busquedas;
    private javax.swing.JButton Insertar;
    private javax.swing.JLabel NombreTabla;
    private javax.swing.JTable TablaVisible;
    private javax.swing.JButton VolverLogeo;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_codigo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nombreAdmin;
    private javax.swing.JLabel sexo;
    // End of variables declaration//GEN-END:variables
}
