/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Principal.VentanaDeInicio;
import Beans.Alumnos;
import Utilidades.BusquedasMongo;
import VentanasProfesor.ListadoAlumnos;
import VentanasProfesor.VentanaChatProfesor;
import VentanasProfesor.VentanaFaltasAlumnos;
import VentanasProfesor.VentanaFaltasProfesor;
import VentanasProfesor.VentanaNotas;
import VentanasProfesor.VentanaVisualizarAlumno;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author 3medi
 */
public class VentanaProfesor extends javax.swing.JFrame {

    private VentanaDeInicio ventanaDeInicio;
    private BusquedasMongo buscar;
    private DBCursor cursor;
    private VentanaNotas ventanaNotas;
    private VentanaFaltasProfesor ventanaFaltasProfesor;
    private VentanaFaltasAlumnos ventanaFaltasAlumno;
    private VentanaVisualizarAlumno ventanaAlumno;
    private ListadoAlumnos listado;
    private VentanaEnviarCorreos ventanaEnviarCorreos;
    private VentanasProfesor.VentanaChatProfesor chat;

    /**
     * Creates new form VentanaProfesor
     *
     * @param ventanaDeInicio
     */
    //Creamos un constructor que reciba la ventana de incio
    public VentanaProfesor(VentanaDeInicio ventanaDeInicio) {
        initComponents();
        this.setVisible(true);
        setLocationRelativeTo(null);
        this.ventanaDeInicio = ventanaDeInicio;

        ImageIcon imagen = new ImageIcon(getClass().getResource("../Imagenes/38e01f84707332276df64d1260f844d6.jpg"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(icono);
        this.repaint();
    }

    //Para evitar que puedan abrir esta ventana sin pasar por el logeo
    private VentanaProfesor() {
        System.out.println("Para acceder a la aplicación necesita iniciar desde el login.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nombreProfesor = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        jLabel_codigo = new javax.swing.JLabel();
        Busquedas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        correoElectronico = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonNotas = new javax.swing.JButton();
        jButtonFaltas = new javax.swing.JButton();
        jButtonListadoAlumno = new javax.swing.JButton();
        Mensajeria = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        nombreProfesor.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        nombreProfesor.setText("Profesor");

        sexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-50.png"))); // NOI18N
        sexo.setText("jLabel7");

        jLabel_codigo.setFont(new java.awt.Font("Baskerville Old Face", 2, 14)); // NOI18N
        jLabel_codigo.setText("codigo");

        Busquedas.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N
        Busquedas.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 2, 18)); // NOI18N
        jLabel8.setText("id Alumno");

        jButtonBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-acercar-20.png"))); // NOI18N
        jButtonBuscar.setToolTipText("Buscar usuario por id");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        correoElectronico.setBackground(new java.awt.Color(255, 255, 255));
        correoElectronico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-inicio-de-sesión-de-gmail-40.png"))); // NOI18N
        correoElectronico.setToolTipText("Boton para enviar correos electronicos");
        correoElectronico.setBorder(null);
        correoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoElectronicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Busquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173)
                .addComponent(correoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Busquedas)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(correoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel_codigo)))))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sexo)
                .addGap(31, 31, 31))
        );

        jPanel3.setBackground(new java.awt.Color(102, 0, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        botonVolver.setBackground(new java.awt.Color(0, 0, 0));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-volver-50.png"))); // NOI18N
        botonVolver.setToolTipText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        jPanel13.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Controles Profesor");

        jButtonNotas.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNotas.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        jButtonNotas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-agregar-regla-50.png"))); // NOI18N
        jButtonNotas.setText("Asignaturas");
        jButtonNotas.setToolTipText("Notas");
        jButtonNotas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNotas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonNotas.setIconTextGap(25);
        jButtonNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotasActionPerformed(evt);
            }
        });

        jButtonFaltas.setBackground(new java.awt.Color(0, 0, 0));
        jButtonFaltas.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        jButtonFaltas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFaltas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-historial-de-retrasos-50.png"))); // NOI18N
        jButtonFaltas.setText("Nueva falta");
        jButtonFaltas.setToolTipText("Asitencia");
        jButtonFaltas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonFaltas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonFaltas.setIconTextGap(25);
        jButtonFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFaltasActionPerformed(evt);
            }
        });

        jButtonListadoAlumno.setBackground(new java.awt.Color(0, 0, 0));
        jButtonListadoAlumno.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
        jButtonListadoAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListadoAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-estudiantes-50.png"))); // NOI18N
        jButtonListadoAlumno.setText("Estudiantes");
        jButtonListadoAlumno.setToolTipText("Listado de estudiantes");
        jButtonListadoAlumno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonListadoAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonListadoAlumno.setIconTextGap(25);
        jButtonListadoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListadoAlumnoActionPerformed(evt);
            }
        });

        Mensajeria.setBackground(new java.awt.Color(0, 0, 0));
        Mensajeria.setFont(new java.awt.Font("Baskerville Old Face", 2, 24)); // NOI18N
        Mensajeria.setForeground(new java.awt.Color(255, 255, 255));
        Mensajeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-crear-nueva-entrada-de-niño-50.png"))); // NOI18N
        Mensajeria.setText("Chat alumno");
        Mensajeria.setToolTipText("Chat interno entre alumno y profesor");
        Mensajeria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mensajeria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Mensajeria.setIconTextGap(25);
        Mensajeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MensajeriaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestión tablas");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chat interno");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(jButtonNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonFaltas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonListadoAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Mensajeria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jButtonNotas)
                .addGap(30, 30, 30)
                .addComponent(jButtonFaltas)
                .addGap(31, 31, 31)
                .addComponent(jButtonListadoAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addComponent(Mensajeria)
                .addGap(35, 35, 35)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscar = new BusquedasMongo();

        //En el caso de que no haya insertado datos en las busquedas
        if (Busquedas.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No ha puesto ninguna id.");
        } else {
            //Buscamos al usuario por la id
            cursor = buscar.buscarUsuarioId(Integer.parseInt(Busquedas.getText()));
            System.out.println(cursor.size());

            try {
                //Si encontramos al alumno 
                if (cursor.size() != 0) {
                    try {
                        //Mandamos la información del alumno
                        while (cursor.hasNext()) {
                            Alumnos alumno = new Alumnos((BasicDBObject) cursor.next());
                            ventanaAlumno = new VentanaVisualizarAlumno(Integer.parseInt(Busquedas.getText()), Integer.parseInt(jLabel_codigo.getText()));
                            ventanaAlumno.getNombreAlumno().setText(alumno.getNombreAlumno());
                        }
                    } catch (NullPointerException e) {

                    }
                }
                if (cursor.size() == 0) {
                    JOptionPane.showMessageDialog(this, "No se ha encontrado al alumno con el codigo  " + Busquedas.getText());
                    Busquedas.setText("");

                }

            } finally {
                cursor.close();

            }

        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void correoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoElectronicoActionPerformed
        // Sacamos la ventana de gestión de correo electronico
        ventanaEnviarCorreos = new VentanaEnviarCorreos(1);
    }//GEN-LAST:event_correoElectronicoActionPerformed

    private void MensajeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MensajeriaActionPerformed
        // Sacamos el chat interno entre profesor y alumno
        if (chat == null) {
            chat = new VentanaChatProfesor(this);
        }else{
            JOptionPane.showMessageDialog(this, "Ya se inició el chat");
           
        }
    }//GEN-LAST:event_MensajeriaActionPerformed

    private void jButtonListadoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListadoAlumnoActionPerformed

        //Sacamos el listado de alumnos
        listado = new ListadoAlumnos(Integer.parseInt(jLabel_codigo.getText()));
    }//GEN-LAST:event_jButtonListadoAlumnoActionPerformed

    private void jButtonFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFaltasActionPerformed

        //Boton que se te da la opción de ir a la ventana de las faltas del profesor o del alumno
        String[] options = {"Profesor", "Alumno"};
        int seleccion = JOptionPane.showOptionDialog(null, "Seleccione la opción que desea", "Seleccion faltas", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (seleccion == 0) {
            System.out.println("Profesor");
            ventanaFaltasProfesor = new VentanaFaltasProfesor(this);
        }
        if (seleccion == 1) {
            System.out.println("Alumno");
            ventanaFaltasAlumno = new VentanaFaltasAlumnos(this);
        }
    }//GEN-LAST:event_jButtonFaltasActionPerformed

    private void jButtonNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotasActionPerformed

        //Damos paso a la ventana de asignaturas
        ventanaNotas = new VentanaNotas(Integer.parseInt(jLabel_codigo.getText()));
    }//GEN-LAST:event_jButtonNotasActionPerformed

    //Boton volver a la ventana de logeo
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed

        //Salimos de la ventana, en el caso de que haya alguna ventana asociada a esta se cierra también
        int advertencia = JOptionPane.showConfirmDialog(null, "¿Está seguro de volver al login? Se perderán los datos");

        if (advertencia == JOptionPane.YES_OPTION) {
            dispose();
            System.out.println("");
            if (ventanaAlumno != null) {
                System.out.println("Cerramos la visualización de alumnos.");
                ventanaAlumno.dispose();
            }
            if (listado != null) {
                System.out.println("Cerramos el listado de alumnos.");
                listado.dispose();
            }
            if (ventanaEnviarCorreos != null) {
                System.out.println("Cerramos la gestión de correos.");
                ventanaEnviarCorreos.dispose();
            }
            if (ventanaNotas != null) {
                System.out.println("Cerramos la ventana de asignaturas");
                ventanaNotas.dispose();
            }
            if (chat != null) {
                System.out.println("Cerramos el chat del profesor.");
                chat.dispose();
            }
            if (ventanaFaltasAlumno != null) {
                System.out.println("Cerramos las faltas de los alumnos.");
                ventanaFaltasAlumno.dispose();
            }
            if (ventanaFaltasProfesor != null) {
                System.out.println("Cerramos las faltas de los profesores.");
                ventanaFaltasProfesor.dispose();
            }
            ventanaDeInicio.setVisible(true);
        }
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaProfesor().setVisible(true);
            }
        });
    }
    //Zona de gets and sets

    public JLabel getSexo() {
        return sexo;
    }

    public void setSexo(JLabel sexo) {
        this.sexo = sexo;
    }

    public JLabel getjLabel_codigo() {
        return jLabel_codigo;
    }

    public void setjLabel_codigo(JLabel jLabel_codigo) {
        this.jLabel_codigo = jLabel_codigo;
    }

    public JLabel getNombreProfesor() {
        return nombreProfesor;
    }

    public void setNombreProfesor(JLabel nombreProfesor) {
        this.nombreProfesor = nombreProfesor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Busquedas;
    private javax.swing.JButton Mensajeria;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton correoElectronico;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonFaltas;
    private javax.swing.JButton jButtonListadoAlumno;
    private javax.swing.JButton jButtonNotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_codigo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombreProfesor;
    private javax.swing.JLabel sexo;
    // End of variables declaration//GEN-END:variables
}
